# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: rails_dev
#   pool: 5
#   username: vivek
#   password: Feeltheair
#   socket: /tmp/mysql.sock

development:
   adapter: mysql2
   database: Rails_DB
   username: root
   password: Feelthe@1r
   socket: /tmp/mysql.sock
   #host: 127.0.0.1
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   timeout: 5000

# development:
#    adapter: mysql2
#    database: Rails_DB
#    username: root
#    password: Feelthe@1r
#    host: 127.0.0.1
#    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#    timeout: 5000
  
# test:
#    adapter: mysql2
#    database: Rails_DB
#    username: root
#    password: Feelthe@1r
#    host: localhost
#    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#    timeout: 5000

production:
   adapter: mysql2
   database: Rails_DB
   username: root
   password: Feelthe@1r
   #host: localhost
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   timeout: 5000